### PR TITLE
Graphql deploy and sanity-ui bugfixes

### LINKED ISSUE #36: Deploying Graphql
When I run the command `sanity graphql deploy` I receive this error:

```
TypeError: Cannot read property 'get' of undefined
    at o (~/Path-to-projct/sanity/node_modules/media-chrome/dist/index.js:82:259)
    at ~/Path-to-projct/sanity/node_modules/media-chrome/dist/index.js:82:1574
    at Object.<anonymous> (~/Path-to-projct/sanity/node_modules/media-chrome/dist/index.js:792:1271)
```

After downgrading to version `0.3.4` I was able to deploy again without any problems.

### LINKED ISSUE #37: Error: Cannot read property 'from' of undefined
Receiving error message 'Error: Cannot read property 'from' of undefined' in Sanity when trying to upload video and/or browsing selecting video. See loom here https://www.loom.com/share/475aed66dc724aa1bfe60cad3f1e77d6

This is with a fresh install of Sanity. Steps I took:

1. Sanity init
2. Chose the movie schema when creating sandbox Sanity
3. Did 'sanity install mux-input'
4. Added the schema in the quick start
5. Added new video reference in movie.js schema
6. Sanity start
7. Tried uploading MP4 video file
8. Upload works, but throws error message at end and won't display video
9. Refreshing, browse to select video I can see video uploaded but cannot select

The console error message is:
`react-dom.development.js:328 Uncaught TypeError: Cannot read property 'from' of undefined
    at Object.onSelect (Input.js:397)
    at SelectAsset.select (SelectAsset.js:98)
    at SelectAsset.select (react-hot-loader.development.js:717)
    at SelectAsset.js:40
    at HTMLUnknownElement.callCallback (react-dom.development.js:189)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:238)
    at invokeGuardedCallback (react-dom.development.js:293)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:307)
    at executeDispatch (react-dom.development.js:390)
    at executeDispatchesInOrder (react-dom.development.js:412)
(anonymous) @ Input.js:397
select @ SelectAsset.js:98
select @ react-hot-loader.development.js:717
(anonymous) @ SelectAsset.js:40
callCallback @ react-dom.development.js:189
invokeGuardedCallbackDev @ react-dom.development.js:238
invokeGuardedCallback @ react-dom.development.js:293
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:307
executeDispatch @ react-dom.development.js:390
executeDispatchesInOrder @ react-dom.development.js:412
executeDispatchesAndRelease @ react-dom.development.js:3279
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:3288
forEachAccumulated @ react-dom.development.js:3260
runEventsInBatch @ react-dom.development.js:3305
runExtractedPluginEventsInBatch @ react-dom.development.js:3515
handleTopLevel @ react-dom.development.js:3559
batchedEventUpdates$1 @ react-dom.development.js:21872
batchedEventUpdates @ react-dom.development.js:796
dispatchEventForLegacyPluginEventSystem @ react-dom.development.js:3569
attemptToDispatchEvent @ react-dom.development.js:4268
dispatchEvent @ react-dom.development.js:4190
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11040
discreteUpdates$1 @ react-dom.development.js:21888
discreteUpdates @ react-dom.development.js:807
dispatchDiscreteEvent @ react-dom.development.js:4169
createStore.js:30 Error: Invalid call to useReporter(field-video.video): A component reporting on "field-video.video" is already mounted in the subtree. Make sure that all reporters within the same <Tracker> subtree have unique ids.
    at add (createStore.js:30)
    at createUseReporter.js:42
    at commitHookEffectListMount (react-dom.development.js:19732)
    at commitLifeCycles (react-dom.development.js:19788)
    at commitLayoutEffects (react-dom.development.js:22804)
    at HTMLUnknownElement.callCallback (react-dom.development.js:189)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:238)
    at invokeGuardedCallback (react-dom.development.js:293)
    at commitRootImpl (react-dom.development.js:22542)
    at unstable_runWithPriority (scheduler.development.js:653)`

Help please! :)

### PR DESCRIPTION
**Pull request by KimPaow**
WIP

This PR aims to solve two main issues:
- e6b7990 Fixes #37 - some older versions of the studio had issues with sanity UI, by wrapping the plugin in its own theme provider this should make sure that those versions of the studio should still work, but also has the downside that the plugin will not benefit from updates to sanity-ui.
- bac4d65 Fixes #36 - Upgrade media-chrome to v0.1.1 in order to fix a bug that caused the `sanity graphql deploy` command to fail.

### CODE REVIEW

**Comment by KimPaow** [comment]
@rexxars do you have any thoughts on e6b7990 as a fix for #37? Any other downsides to doing it this way?

**Review by KimPaow — COMMENTED** [review]
This is to get rid of the warning regarding duplicate versions of styled-components being installed in the studio

**Comment by judofyr** [comment]
> do you have any thoughts on [e6b7990](https://github.com/sanity-io/sanity-plugin-mux-input/commit/e6b799083723b961c9097b6177e1e1c415069c23) as a fix for #37? Any other downsides to doing it this way?

The linked issue has already been fixed in Sanity v2.12.2. Do we still need this fix?

**Comment by KimPaow** [comment]
> The linked issue has already been fixed in Sanity v2.12.2. Do we still need this fix?

We were thinking that this would make sure that it works for older versions of the studio, or in case a similar bug shows up again, mostly we wanted to include it to discuss the tradeoffs. Are there any downsides to including this fix beyond it not being very pretty?

**Comment by rexxars** [comment]
The downside of the approach with a separate theme provider is that people who have customized their studio theme won't have those customizations applied within the mux plugin. It's a change that can be rolled back later, so merging this for now and we can revisit the theming later.

**Pull request merged**
