### PR TITLE
Use 'document' type for Mux assets

### PR DESCRIPTION
**Pull request by tkdave**
Consider using 'document' for mux video assets so the types show up in GraphQL. Side-effect is that these documents may show up in auto-generated studio menus.

### CODE REVIEW

**Comment by tkdave** [comment]
Note: You can hide Mux Assets from the ‘New document’ menu by providing a custom ‘newDocumentStructure’ and filtering out the mux assets. 

Reference: https://www.sanity.io/docs/initial-value-templates#configuring-the-new-document-menu-56b4073ca73a

Sample `newDocumentStructure.js`:
```
import S from '@sanity/base/structure-builder'
export default [
  ...S.defaultInitialValueTemplateItems().filter(i => i.spec.id !== 'mux.videoAsset')
]
```

**Comment by tkdave** [comment]
This definitely needs testing. Now I’m getting reference errors when trying to remove assets. They can’t be deleted due to existing reference (but it’s the reference to the current doc that I’m trying to remove in the first place). Also, the checkbox labels in the delete dialog are now missing? (not sure how that would be related, investigating...)

**Comment by stipsan** [comment]
Don't know when but I see it's already changed to `mux.videoAsset` :relaxed:

**Comment by stipsan** [comment]
Don't know when but I see it's already changed to `mux.videoAsset` :relaxed:

**Pull request closed without merging**
