### PR TITLE
Add support for max_resolution_tier

### PR DESCRIPTION
**Pull request by phmasek**
Addresses https://github.com/sanity-io/sanity-plugin-mux-input/issues/324

### CODE REVIEW

**Comment by kritzware** [comment]
Any updates on when this will be released?

**Comment by TomasCarlson** [comment]
Much needed pull

**Comment by antonio-moton** [comment]
> Any updates on when this will be released?

I am looking forward to this release as well. Any Update?

**Comment by phmasek** [comment]
@stipsan Would you mind please reviewing this PR? :)

**Comment by phmasek** [comment]
@antonio-moton @kritzware I have researched this further and it seems that my PR wouldn't be enough to add the support for `max_resolution_tier` unfortunately. 

The resulting upload request sent to the MUX API does not include the additional parameters (see picture from MUX request logs) although I've added the options in the plugin.
It seems like the plugin sends the upload request to Sanity's servers which processes the upload to MUX by proxy via their servers. I believe the Sanity backend would also have to be extended to fully support the additional parameters.

image

**Comment by kritzware** [comment]
You're right @antonio-moton, I noticed this too when I made the same changes locally (as documented in #324), so unfortunately it looks like we'll have to wait for Sanity to make the necessary internal changes.

**Comment by kritzware** [comment]
Can anyone from the Sanity team provide an update on the status of this feature request?

**Comment by evenwestvang** [comment]
We're in discussion with MUX about this. We'll get back to you.

**Review by stipsan — APPROVED** [review]
Thanks!

**Comment by hdoro** [comment]
@phmasek thank you so much for your work on this.

Unfortunately, we're working on this feature with a different approach and won't be able to merge your PR. I have taken portions of your documentation suggestion, though - thank you Philip!

**Pull request closed without merging**
