### PR TITLE
fix: enable dynamic chunk size in upChunk

### PR DESCRIPTION
**Pull request by jaredsmith**
Introduce dynamic chunk sizes in upChunk, as requested in #86

### CODE REVIEW

**Review by stipsan — APPROVED** [review]
Thank you! ✨

**Comment by jaredsmith** [comment]
I don't pretend to understand the build system you're using, but it looks like the build failure wasn't necessarily related to my PR.  Or am I missing something obvious?

**Comment by jaredsmith** [comment]
@stipsan Any response to my questions above?  Is this just an issue with the build system, or is there an issue with my PR that is preventing the code from building successfully?

**Comment by stipsan** [comment]
Hi @jaredsmith! Sorry for the delay, it appears to be a problem in parcel that happens if using TypeScript `4.8`.
I've downgraded it to `4.7` so we should be good to go now 👍

**Pull request merged**
